# Generated by Django 3.0.7 on 2020-08-05 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('cash_amount', models.FloatField()),
                ('card_amount', models.FloatField()),
                ('cashbox_morning', models.FloatField()),
                ('expense_cash', models.FloatField(blank=True, default=0)),
                ('expense_card', models.FloatField(blank=True, default=0)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Бармен')),
            ],
        ),
    ]
