# Generated by Django 3.0.7 on 2020-08-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(unique=True, verbose_name='Дата'),
        ),
    ]
