# Generated by Django 3.0.7 on 2020-08-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200805_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='expense_card',
        ),
        migrations.AddField(
            model_name='report',
            name='cashbox_cash_added',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
